-- CREATE TABLE IF NOT EXISTS users
-- (
--     id    SERIAL PRIMARY KEY ,
--     username  VARCHAR(200) NOT NULL ,
--     email VARCHAR(254) NOT NULL ,
--     department VARCHAR(50)  NOT NULL,
--     group_number INT
-- );
-- DROP TABLE IF EXISTS users;